First importation of general data.

In [1]:
import pandas as pd
import numpy as np
from sklearn import *
import matplotlib.pyplot as plt

df = pd.read_csv("KaDo.csv")

First visualisation of data. First ten rows.

In [2]:
df.head(10)

,TICKET_ID,MOIS_VENTE,PRIX_NET,FAMILLE,UNIVERS,MAILLE,LIBELLE,CLI_ID
0,35592159,10,1.67,HYGIENE,HYG_DOUCHE JARDINMONDE,HYG_JDM,GD JDM4 PAMPLEMOUSSE FL 200ML,1490281
1,35592159,10,1.66,HYGIENE,HYG_DOUCHE JARDINMONDE,HYG_JDM,GD JDM4 PAMPLEMOUSSE FL 200ML,1490281
2,35592159,10,7.45,SOINS DU VISAGE,VIS_CJOUR Jeunes Specifique,VIS_JEUNE_ET_LEVRE,CR JR PARF BIO.SPE AC.SENT.50ML,1490281
3,35592159,10,5.95,SOINS DU VISAGE,VIS_DEMAQ AAAR,VIS_AAAR_DEMAQLOTION,EAU MICELLAIRE 3 THES FL200ML,1490281
4,35592159,10,1.67,HYGIENE,HYG_DOUCHE JARDINMONDE,HYG_JDM,GD JDM4 TIARE FL 200ML,1490281
5,35509899,9,13.00,PARFUMAGE,PARF_EAUX PARFUMS,PARF_PARFUM,EDT UN MATIN AU JARDIN 100ML MUGUET,13290776
6,35509899,9,5.50,SOINS DU CORPS,CORPS_LAIT HUILE PLAISIRNATURE,CORPS_HYDR_LAIT_HUILE,LAIT VELOUTE COCO PN2 400ML,13290776
7,36417517,12,1.75,HYGIENE,HYG_DOUCHE PARFUMS,HYG_PARFUMEE,GD LILAS FP FL200ML,13290776
8,36417517,12,1.76,HYGIENE,HYG_DOUCHE PARFUMS,HYG_PARFUMEE,GD LILAS FP FL200ML,13290776
9,36417517,12,2.25,HYGIENE,HYG_DOUCHE PARFUMS,HYG_PARFUMEE,GD LILAS FP FL200ML,13290776

Extract unique Client Id

In [3]:
client = df["CLI_ID"].unique()
print(len(client))
client[1]

853514

13290776

try to extract mean price paid by each client

In [4]:
PriceClient = df.loc[:, ["PRIX_NET", "CLI_ID"]]

MeanPrice = PriceClient.groupby("CLI_ID").mean()
MaxPrice = PriceClient.groupby("CLI_ID").max()
MinPrice = PriceClient.groupby("CLI_ID").min()
MeanPrice.head()

          PRIX_NET
CLI_ID
1490281   3.680000
13290776  6.166667
20163348  7.450000
20200041  3.350000
20561854  2.350000

In [5]:
MaxPrice.head()

          PRIX_NET
CLI_ID
1490281       7.45
13290776     13.00
20163348      7.45
20200041      5.45
20561854      2.95

In [6]:
MinPrice.head()

          PRIX_NET
CLI_ID
1490281       1.66
13290776      1.75
20163348      7.45
20200041      1.25
20561854      1.65

extract month by client ???

In [7]:
MClient = df.loc[:, ["MOIS_VENTE", "CLI_ID"]]

# monthUnique = MClient.groupby("CLI_ID").value_counts()
# monthUnique.head(15)
MClient.groupby(["CLI_ID", "MOIS_VENTE"]).count().sort_values("CLI_ID").groupby(level=0).tail(1)

Empty DataFrame
Columns: []
Index: [(1490281, 10), (13290776, 12), (20163348, 1), (20200041, 1), (20561854, 3), (20727324, 1), (20791601, 5), (21046542, 2), (21239163, 1), (21351166, 1), (21497331, 4), (21504227, 2), (21514622, 5), (69813934, 6), (71891681, 12), (85057203, 8), (85841284, 6), (90822328, 6), (93806295, 1), (100023116, 1), (100064590, 12), (126716008, 10), (131204016, 3), (169985247, 11), (191914645, 7), (195207210, 4), (206111880, 1), (242424645, 4), (243624087, 12), (275493987, 7), (300240190, 5), (321933797, 7), (336948609, 12), (354587579, 7), (355512954, 8), (356832238, 11), (356998310, 12), (358464805, 7), (359489151, 3), (360340862, 6), (360778261, 12), (362128564, 4), (364610105, 8), (365845758, 12), (366515154, 5), (372228560, 12), (372367788, 5), (372402389, 4), (372658871, 12), (373876169, 7), (374498062, 4), (375178968, 12), (376616710, 9), (376679774, 11), (377424198, 2), (377526421, 2), (377897004, 10), (379033690, 6), (379341548, 8), (379731029, 6), (379770712, 7), (380273582, 9), (380648947, 9), (380922485, 11), (382969442, 10), (382981257, 4), (383061124, 7), (383066678, 9), (383922927, 2), (384219852, 6), (384597572, 12), (384887650, 12), (385663785, 4), (385760870, 10), (386310148, 2), (387432999, 4), (387473292, 11), (389021849, 12), (389163338, 7), (389725384, 7), (389982892, 10), (390182509, 11), (390189439, 12), (390210524, 10), (390457373, 1), (390916120, 1), (390926961, 11), (391201942, 11), (391365450, 9), (391832994, 11), (392034500, 2), (392363973, 7), (396251217, 3), (399874122, 11), (400457009, 7), (401255773, 2), (401489663, 4), (405958556, 3), (406101429, 5), (432300011, 11), ...]

[853514 rows x 0 columns]

Get univers and Famille

In [8]:
UniversClient = df.loc[:, ["UNIVERS", "CLI_ID"]]
# univOrga = UniversClient.groupby(["CLI_ID", "UNIVERS"]).value_counts().max(level=0)
# univOrga = UniversClient.groupby(["CLI_ID", "UNIVERS"]).value_counts()
# print(univOrga)
UniversClient.groupby(["CLI_ID", "UNIVERS"]).count().sort_values("CLI_ID").groupby(level=0).tail(1)
#UniversClient.groupby("CLI_ID").count().sort_values("CLI_ID").groupby(level=0).tail(1)

Empty DataFrame
Columns: []
Index: [(1490281, VIS_DEMAQ AAAR), (13290776, PARF_EAUX PARFUMS), (20163348, MAQ_LEV RAL Brillance), (20200041, VIS_CJOUR Jeunes Specifique), (20561854, MAQ_ONG Vernis LUM), (20727324, CORPS_LAIT HUILE AUTRES), (20791601, MAQ_TEINT Fard a joues), (21046542, CAP_AP SHAMP), (21239163, HYG_DOUCHE PLAISIRNATURE), (21351166, VIS_DEMAQ PUR), (21497331, MAQ_LEV RAL Lum4), (21504227, VIS_SOIN LEVRES), (21514622, MAQ_LEV RAL GrdRouge), (69813934, HYG_DOUCHE PARFUMS), (71891681, CORPS_LAIT HUILE PLAISIRNATURE), (85057203, MAQ_ONG Vernis CN), (85841284, MAQ_YEUX Eyeliner), (90822328, MAQ_YEUX Crayons), (93806295, HYG_DOUCHE JARDINMONDE), (100023116, HYG_DOUCHE PLAISIRNATURE), (100064590, HYG_DOUCHE EDT NOEL), (126716008, PARF_PARF ET EAU DE PARF), (131204016, HYG_DOUCHE JARDINMONDE), (169985247, MAQ_ONG Vernis LUM), (191914645, HYG_DOUCHE PLAISIRNATURE), (195207210, HYG_DOUCHE JARDINMONDE), (206111880, VIS_SOIN LEVRES), (242424645, MAQ_ONG Vernis LUM), (243624087, MAQ_ONG Vernis CN), (275493987, MAQ_ONG AUTRES), (300240190, CORPS_LAIT HUILE MONOI), (321933797, MAQ_TEINT Poudres), (336948609, MAQ_TEINT Poudres), (354587579, HYG_DOUCHE CULTUREBIO), (355512954, SOL_APRES SOLEIL), (356832238, CORPS_HYDRA NOURRISANT), (356998310, MAQ_TEINT Fard a joues), (358464805, HYG_DOUCHE JARDINMONDE), (359489151, CORPS_LAIT HUILE PARFUMS), (360340862, MAQ_YEUX Mascara Specifique), (360778261, MAQ_TEINT Poudres), (362128564, VIS_TRAIT AAAR), (364610105, VIS_CNUIT AAAR), (365845758, CORPS_HYDRA NOURRISANT), (366515154, PARF_PARF ET EAU DE PARF), (372228560, PARF_PARF ET EAU DE PARF), (372367788, CORPS_SOIN PIEDS ET JAMBES), (372402389, MAQ_ONG Vernis CN), (372658871, MAQ_LEV RAL Brillance), (373876169, MAQ_YEUX Fard), (374498062, PARF_EAUX PLAISIR NATURE), (375178968, PARF_EAUX PARFUMS), (376616710, MAQ_YEUX Mascara Specifique), (376679774, VIS_SOIN LEVRES), (377424198, HYG_DOUCHE JARDINMONDE), (377526421, MAQ_TEINT Poudres), (377897004, VIS_DEMAQ BLEUET), (379033690, PARF_PARF ET EAU DE PARF), (379341548, PARF_PARF ET EAU DE PARF), (379731029, CAP_TRAITEMENT), (379770712, VIS_SOIN LEVRES), (380273582, MAQ_ONG AUTRES), (380648947, CORPS_SOIN DES MAINS), (380922485, MAQ_ONG Vernis LUM), (382969442, VIS_CJOUR Jeunes Specifique), (382981257, MAQ_YEUX Stylos), (383061124, PARF_EAUX PARFUMS), (383066678, PARF_PARF ET EAU DE PARF), (383922927, VIS_SOIN LEVRES), (384219852, SOL_AUTOBRONZANTS), (384597572, PARF_EAUX DE COLOGNE), (384887650, MAQ_LEV AUTRES), (385663785, MAQ_TEINT Poudres), (385760870, PARF_PARF ET EAU DE PARF), (386310148, MAQ_TEINT Font teint), (387432999, CAP_SHAMP TSCHEVEUX), (387473292, VIS_LOTIONS Jeunes Specifique), (389021849, HYG_BAIN SEL HUILE PERLE), (389163338, HYG_DOUCHE JARDINMONDE), (389725384, VIS_SOIN LEVRES), (389982892, VIS_SOIN LEVRES), (390182509, CORPS_HYDRA NOURRISANT), (390189439, VIS_SOIN LEVRES), (390210524, MAQ_LEV AUTRES), (390457373, MAQ_TEINT Poudres), (390916120, VIS_SOIN LEVRES), (390926961, HYG_SAVONS), (391201942, VIS_DEMAQ BLEUET), (391365450, MAQ_LEV BRILLANT), (391832994, HYG_DEO PARFUMS), (392034500, HYG_DOUCHE JARDINMONDE), (392363973, CORPS_SOIN PIEDS ET JAMBES), (396251217, VIS_CJOUR Jeunes Specifique), (399874122, CORPS_HYDRA NOURRISANT), (400457009, CORPS_SOIN PIEDS ET JAMBES), (401255773, VIS_CJOUR AAAR), (401489663, VIS_DEMAQ BLEUET), (405958556, VIS_CJOUR Jeunes Specifique), (406101429, VIS_DEMAQ AAAR), (432300011, CORPS_LAIT HUILE PARFUMS), ...]

[853514 rows x 0 columns]

In [9]:
FamilleClient = df.loc[:, ["FAMILLE", "CLI_ID"]]
#famOrga = FamilleClient.groupby("CLI_ID").value_counts()
FamilleClient.groupby(["CLI_ID", "FAMILLE"]).count().sort_values("CLI_ID").groupby(level=0).tail(1)

Empty DataFrame
Columns: []
Index: [(1490281, SOINS DU VISAGE), (13290776, SOINS DU CORPS), (20163348, MAQUILLAGE), (20200041, SOINS DU VISAGE), (20561854, CAPILLAIRES), (20727324, SOINS DU CORPS), (20791601, SOINS DU CORPS), (21046542, MAQUILLAGE), (21239163, SOINS DU CORPS), (21351166, SOINS DU VISAGE), (21497331, SOINS DU CORPS), (21504227, SOINS DU VISAGE), (21514622, SOINS DU CORPS), (69813934, HYGIENE), (71891681, SOINS DU CORPS), (85057203, MAQUILLAGE), (85841284, SOLAIRES), (90822328, MAQUILLAGE), (93806295, HYGIENE), (100023116, HYGIENE), (100064590, SOLAIRES), (126716008, PARFUMAGE), (131204016, SOINS DU VISAGE), (169985247, HYGIENE), (191914645, HYGIENE), (195207210, SOINS DU VISAGE), (206111880, SOINS DU VISAGE), (242424645, MAQUILLAGE), (243624087, MAQUILLAGE), (275493987, MAQUILLAGE), (300240190, SOINS DU CORPS), (321933797, SOLAIRES), (336948609, HYGIENE), (354587579, HYGIENE), (355512954, SOLAIRES), (356832238, SOINS DU CORPS), (356998310, CAPILLAIRES), (358464805, HYGIENE), (359489151, SOINS DU CORPS), (360340862, SOINS DU CORPS), (360778261, SOINS DU VISAGE), (362128564, HYGIENE), (364610105, SOINS DU VISAGE), (365845758, SOLAIRES), (366515154, MAQUILLAGE), (372228560, PARFUMAGE), (372367788, SOINS DU VISAGE), (372402389, MAQUILLAGE), (372658871, SOLAIRES), (373876169, MAQUILLAGE), (374498062, SOINS DU CORPS), (375178968, PARFUMAGE), (376616710, SOINS DU VISAGE), (376679774, PARFUMAGE), (377424198, HYGIENE), (377526421, MAQUILLAGE), (377897004, SOINS DU VISAGE), (379033690, PARFUMAGE), (379341548, PARFUMAGE), (379731029, SOINS DU VISAGE), (379770712, SOINS DU VISAGE), (380273582, MAQUILLAGE), (380648947, MAQUILLAGE), (380922485, SOINS DU CORPS), (382969442, SOINS DU VISAGE), (382981257, SOINS DU VISAGE), (383061124, PARFUMAGE), (383066678, PARFUMAGE), (383922927, SOINS DU VISAGE), (384219852, SOLAIRES), (384597572, SOINS DU CORPS), (384887650, SOLAIRES), (385663785, SOINS DU VISAGE), (385760870, HYGIENE), (386310148, MAQUILLAGE), (387432999, HYGIENE), (387473292, SOINS DU VISAGE), (389021849, SOINS DU VISAGE), (389163338, HYGIENE), (389725384, SOINS DU VISAGE), (389982892, SOINS DU VISAGE), (390182509, MAQUILLAGE), (390189439, SOLAIRES), (390210524, SOLAIRES), (390457373, MAQUILLAGE), (390916120, SOINS DU CORPS), (390926961, HYGIENE), (391201942, SOINS DU VISAGE), (391365450, MAQUILLAGE), (391832994, SOINS DU VISAGE), (392034500, SOINS DU CORPS), (392363973, SOINS DU CORPS), (396251217, SOINS DU VISAGE), (399874122, SOINS DU CORPS), (400457009, SOINS DU CORPS), (401255773, MAQUILLAGE), (401489663, SOINS DU VISAGE), (405958556, SOINS DU VISAGE), (406101429, SOINS DU VISAGE), (432300011, SOINS DU CORPS), ...]

[853514 rows x 0 columns]

In [10]:
MailleClient = df.loc[:, ["MAILLE", "CLI_ID"]]
#mailleOrga = MailleClient.groupby("CLI_ID").value_counts()
MailleClient.groupby(["CLI_ID", "MAILLE"]).count().sort_values("CLI_ID").groupby(level=0).tail(1)

Empty DataFrame
Columns: []
Index: [(1490281, VIS_JEUNE_ET_LEVRE), (13290776, PARF_PARFUM), (20163348, MAQ_LEV_RAL_HMG), (20200041, VIS_JEUNE_ET_LEVRE), (20561854, MAQ_ONGLES), (20727324, HYG_JDM), (20791601, MAQ_TEINT), (21046542, HYG_HOMME), (21239163, HYG_PLAISIRNAT_BAIN_SAVON), (21351166, VIS_BIO), (21497331, PARF_PARFUM), (21504227, VIS_JEUNE_ET_LEVRE), (21514622, MAQ_LEV_RAL_HMG), (69813934, HYG_JDM), (71891681, PARF_EDT), (85057203, MAQ_ONGLES), (85841284, MAQ_YEUX_CLASSIQUE), (90822328, HYG_PLAISIRNAT_BAIN_SAVON), (93806295, HYG_JDM), (100023116, HYG_PLAISIRNAT_BAIN_SAVON), (100064590, HYG_MONOI_ET_EDIT_SPEC), (126716008, PARF_PARFUM), (131204016, HYG_JDM), (169985247, CORPS_HYDRA_NOURRI_ET_SOINS), (191914645, HYG_PLAISIRNAT_BAIN_SAVON), (195207210, HYG_JDM), (206111880, VIS_JEUNE_ET_LEVRE), (242424645, MAQ_ONGLES), (243624087, MAQ_ONGLES), (275493987, HYG_PLAISIRNAT_BAIN_SAVON), (300240190, CORPS_MONOI), (321933797, MAQ_LEV_RAL_HMG), (336948609, PARF_PARFUM), (354587579, HYG_CULTUREBIO), (355512954, MAQ_YEUX_CLASSIQUE), (356832238, PARF_PARFUM), (356998310, CAPILLAIRE_AUTRE), (358464805, HYG_JDM), (359489151, PARF_PARFUM), (360340862, HYG_AUTRES), (360778261, MAQ_TEINT), (362128564, HYG_JDM), (364610105, VIS_AAAR_HORS_DEMAQLOTION), (365845758, VIS_JEUNE_ET_LEVRE), (366515154, HYG_JDM), (372228560, PARF_PARFUM), (372367788, VIS_PUR), (372402389, CORPS_HYDRA_NOURRI_ET_SOINS), (372658871, MAQ_LEV_BASPRIX), (373876169, MAQ_YEUX_MASCA_EYEL_FARD), (374498062, PARF_EDT), (375178968, PARF_PARFUM), (376616710, VIS_JEUNE_ET_LEVRE), (376679774, HYG_MONOI_ET_EDIT_SPEC), (377424198, HYG_JDM), (377526421, MAQ_TEINT), (377897004, VIS_AUTRES), (379033690, PARF_PARFUM), (379341548, PARF_PARFUM), (379731029, CORPS_SPA_ET_MINCEUR), (379770712, VIS_PUR), (380273582, MAQ_ONGLES), (380648947, MAQ_ONGLES), (380922485, CORPS_SPA_ET_MINCEUR), (382969442, VIS_PUR), (382981257, VIS_JEUNE_ET_LEVRE), (383061124, CORPS_HYDR_LAIT_HUILE), (383066678, PARF_PARFUM), (383922927, VIS_JEUNE_ET_LEVRE), (384219852, SOLAIRE), (384597572, PARF_PARFUM), (384887650, MAQ_ONGLES), (385663785, MAQ_YEUX_CLASSIQUE), (385760870, PARF_PARFUM), (386310148, MAQ_TEINT), (387432999, CAPILLAIRE_SHAMPOING), (387473292, VIS_JEUNE_ET_LEVRE), (389021849, HYG_JDM), (389163338, HYG_JDM), (389725384, VIS_JEUNE_ET_LEVRE), (389982892, VIS_JEUNE_ET_LEVRE), (390182509, HYG_PARFUMEE), (390189439, VIS_JEUNE_ET_LEVRE), (390210524, MAQ_ONGLES), (390457373, MAQ_TEINT), (390916120, VIS_JEUNE_ET_LEVRE), (390926961, HYG_PLAISIRNAT_BAIN_SAVON), (391201942, VIS_AUTRES), (391365450, MAQ_LEV_BASPRIX), (391832994, VIS_AAAR_HORS_DEMAQLOTION), (392034500, HYG_JDM), (392363973, CORPS_SPA_ET_MINCEUR), (396251217, VIS_JEUNE_ET_LEVRE), (399874122, CORPS_HYDRA_NOURRI_ET_SOINS), (400457009, CORPS_HYDRA_NOURRI_ET_SOINS), (401255773, VIS_JEUNE_ET_LEVRE), (401489663, VIS_AUTRES), (405958556, VIS_JEUNE_ET_LEVRE), (406101429, VIS_AAAR_DEMAQLOTION), (432300011, PARF_PARFUM), ...]

[853514 rows x 0 columns]

In [11]:
famille = df.loc[:, "FAMILLE"]
familleU = famille.unique()
# familleU
len(familleU)

9

In [12]:
maille = df.loc[:, "MAILLE"]
mailleU = maille.unique()
# mailleU
len(mailleU)

34

In [13]:
univers = df.loc[:, "UNIVERS"]
universU = univers.unique()
#universU
len(universU)

105

Another tesd

In [14]:
test1 = df.loc[:, ["CLI_ID", "UNIVERS", "MOIS_VENTE" ,"FAMILLE", "MAILLE"]]
test4 = test1.groupby(["CLI_ID", "UNIVERS", "MOIS_VENTE", "FAMILLE", "MAILLE"]).count().sort_values("CLI_ID").groupby(level=0).tail(1)

In [15]:
test2 = df.loc[:, ["CLI_ID","PRIX_NET"]]
test3 = test2.groupby("CLI_ID").agg([min, max, "mean"])
test5 = test4.join(test3)
test5.to_csv("data.csv")
test5

/Users/user/opt/anaconda3/lib/python3.9/site-packages/pandas/core/frame.py:9130: FutureWarning: merging between different levels is deprecated and will be removed in a future version. (1 levels on the left,2 on the right)
  return merge(

,,,,,"(PRIX_NET, min)","(PRIX_NET, max)","(PRIX_NET, mean)"
CLI_ID,UNIVERS,MOIS_VENTE,FAMILLE,MAILLE,,,
1490281,VIS_DEMAQ AAAR,10,SOINS DU VISAGE,VIS_AAAR_DEMAQLOTION,1.66,7.45,3.680000
13290776,PARF_EAUX PARFUMS,12,PARFUMAGE,PARF_PARFUM,1.75,13.00,6.166667
20163348,MAQ_LEV RAL Brillance,1,MAQUILLAGE,MAQ_LEV_RAL_HMG,7.45,7.45,7.450000
20200041,VIS_CJOUR Jeunes Specifique,1,SOINS DU VISAGE,VIS_JEUNE_ET_LEVRE,1.25,5.45,3.350000
20561854,MAQ_ONG Vernis LUM,3,MAQUILLAGE,MAQ_ONGLES,1.65,2.95,2.350000
...,...,...,...,...,...,...,...
997048745,MAQ_ONG AUTRES,8,MAQUILLAGE,MAQ_ONGLES,4.95,4.95,4.950000
997048751,HYG_DOUCHE PLAISIRNATURE,8,HYGIENE,HYG_PLAISIRNAT_BAIN_SAVON,1.00,13.90,5.760000
997048769,VIS_SOIN LEVRES,10,SOINS DU VISAGE,VIS_JEUNE_ET_LEVRE,1.25,20.90,7.265000
997048777,VIS_SOIN LEVRES,8,SOINS DU VISAGE,VIS_JEUNE_ET_LEVRE,1.50,18.00,3.878947
997385337,SOL_PROTECTEURS SOLAIRES,9,SOLAIRES,SOLAIRE,1.95,11.45,5.193478